### ISSUE TITLE
Form error message

### ISSUE THREAD

**Issue by nieok** [nieok/DolceFarfallaHTML#27]
When validating the forms add a class **form-error** to **form__controls** (refer to #26 ) when validating a form that looks like this 

![df_issue_4](https://user-images.githubusercontent.com/9007597/43323081-4638854e-91b9-11e8-97d2-d84cd365883d.png)

**Comment by nieok** [comment]
In order to validate a form do not use a listener on a button instead use the jquery validation.

Find below an example of both the html and the js needed:


````html
<div class="form-group col-12 col-md-6">
    <label class="holder-label" for="fname">Full name *</label>
    <input id="fname" class="form-control input-name holder-input holder-error-form" type="text" required="">                      
</div>
````

````js
$("form#contactForm").validate({
    errorClass: 'form-error',
    ignore: "",
    highlight: function (element, errorClass, validClass) {
        $(element).parents('.form-group').removeClass(errorClass).addClass(errorClass)
    },
    unhighlight: function (element, errorClass, validClass) {
        $(element).parents('.form-group').removeClass(errorClass).addClass(validClass)
    },
    rules: {},
    messages: {},
    invalidHandler: function (form, validator) {},
    submitHandler: function (form){
        $(form).find(".form-btn-wrapper").addClass("loading");
    }
});
````

Note: All forms need a loader to show once the form is submitted. Please follow the below html structure. 

````html
<div class="form-btn-wrapper">
    <button class="[BUTTONCLASSES]" type="submit">Submit</button>
    <div class="form-btn-loader"></div>
</div>
````

If the form has a notice or a small message, put it outside of the **form-btn-wrapper**. Do not include anything in the **form-btn-wrapper** element.

Once the form is submitted, if valid add the class loading to **form-btn-wrapper**, hide the button and show the loader. 

The loader should be written in html and css only ( do not use gif). 
Loader example: 
````css
.btn-loader {
    border: 4px solid #21479c;
    /* Light grey */
    border-top: 4px solid #fff;
    /* Blue */
    border-radius: 50%;
    width: 34px;
    height: 34px;
    animation: spin 1.7s linear infinite;
    margin: auto;
}

form .form-btn-wrapper:not(.loading) input[type="submit"],
form .form-btn-wrapper:not(.loading) button[type="submit"] {
    display: block;
}

form .form-btn-wrapper.loading input[type="submit"],
form .form-btn-wrapper.loading button[type="submit"] {
    display: none !important;
}

@keyframes spin {
    0% {
        transform: rotate(0deg);
    }
    100% {
        transform: rotate(360deg);
    }
}
````
